version: "2"
services:
  generate_secrets:
    image: bash:5.2.26
    volumes:
      - .:/code
    working_dir: /code
    command: ./generate_secrets
  test_db:
    depends_on:
      generate_secrets:
        condition: service_completed_successfully
    image: postgres:16
    environment:
      POSTGRES_DB: team_sheets
      POSTGRES_PASSWORD_FILE: /run/secrets/db_superuser_password
    ports:
      - 5432:5432
    secrets:
      - db_superuser_password
  setup_db:
    depends_on:
      generate_secrets:
        condition: service_completed_successfully
      test_db:
        condition: service_started
    image: liquibase/liquibase
    volumes:
      - ./db-migrations:/liquibase/changelog
    secrets:
      - db_superuser_password
    command:
    - "--defaultsFile=/liquibase/changelog/liquibase.properties"
    - "update"
    - "--classpath=/liquibase/changelog"
    - "--url=jdbc:postgresql://test_db:5432/team_sheets"
    - "--username=postgres"
    - "--changelog-file=changelog.yaml"
  dev_env:
    depends_on:
      generate_secrets:
        condition: service_completed_successfully
      test_db:
        condition: service_started
      setup_db:
        condition: service_completed_successfully
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.8_3.3.1
    stdin_open: true
    tty: true
    working_dir: /code
    environment:
      DB_HOST: test_db
      DB_PASSWORD_FILE: /run/secrets/db_user_password
    volumes:
      - ./:/code
      - sbt-cache:/home/sbtuser/.cache
    secrets:
      - db_user_password
secrets:
  db_superuser_password:
    file: .secrets/db_superuser.passwd
  db_user_password:
    file: .secrets/db_user.passwd
volumes:
  sbt-cache:


