version: "2"
services:
  dev_env:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.8_3.3.1
    stdin_open: true
    tty: true
    working_dir: /code
    volumes:
      - ./:/code
      - sbt-cache:/home/sbtuser/.cache
volumes:
  sbt-cache:


