#! /usr/bin/env bash

generate_or_read_password() {
  FILENAME=$1
  PASSWORD_LENGTH=$2

  if [ ! -f "$FILENAME" ]; then
    PASSWORD=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$PASSWORD_LENGTH")
    printf "%s" "$PASSWORD" > "$FILENAME"
  else
    PASSWORD=$(cat "$FILENAME")
  fi
}

if [ ! -d .secrets ]; then
  mkdir .secrets
fi

generate_or_read_password ".secrets/db_superuser.passwd" "16"
DB_SUPERUSER_PASSWORD=$PASSWORD

generate_or_read_password ".secrets/db_user.passwd" "16"
DB_USER_PASSWORD=$PASSWORD

cat > db-migrations/liquibase.properties << EOF
changelogFile=changelog.yaml
password=$DB_SUPERUSER_PASSWORD
liquibase.missingPropertyMode=error
EOF

cat > db-migrations/changelog.properties << EOF
db.user.password=$DB_USER_PASSWORD
EOF
